### ISSUE TITLE
program panic's when run with cmemory

### ISSUE THREAD

**Issue by amoghe** [emilymaier/cmemory#1]
I'm excited that this library exists. I'm looking to use it during go tests to ensure that calling my func (which calls into cgo) does not leak memory in C-land.

You can see my usage here: https://github.com/amoghe/go-crypt/commit/30169e876584a7214b9b9399d8b5907ba496ff40

Running `go test -v` fails 

```
goroutine 8 [running]:
runtime.gothrow(0x55ed50, 0xf)
    /usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc208055e08 sp=0xc208055df0
runtime.cmalloc(0x9, 0x1)
    /usr/local/go/src/runtime/cgocall.go:168 +0x76 fp=0xc208055e30 sp=0xc208055e08
github.com/amoghe/go-crypt._Cfunc_CString(0x565250, 0x8, 0x403e78)
    github.com/amoghe/go-crypt/_test/_obj_test/_cgo_gotypes.go:30 +0x32 fp=0xc208055e88 sp=0xc208055e30
github.com/amoghe/go-crypt.Crypt(0x565250, 0x8, 0x567fd0, 0x12, 0x0, 0x0, 0x0, 0x0)
    /home/akshay/go/src/github.com/amoghe/go-crypt/crypt_r.go:46 +0x62 fp=0xc208055ef0 sp=0xc208055e88
github.com/amoghe/go-crypt.TestCheckMemoryAllocation(0xc2080561b0)
    /home/akshay/go/src/github.com/amoghe/go-crypt/crypt_test.go:80 +0x98 fp=0xc208055f78 sp=0xc208055ef0
testing.tRunner(0xc2080561b0, 0x7fe588)
    /usr/local/go/src/testing/testing.go:447 +0xbf fp=0xc208055fd0 sp=0xc208055f78
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208055fd8 sp=0xc208055fd0
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:555 +0xa8b
```

Any ideas on what could be going wrong?

**Comment by emilymaier** [comment]
I'm glad you like the library, but it hasn't been maintained for recent Go versions, which is probably what's causing the problem.

The basic problem is that when your code calls CString(), the runtime calls malloc() on its behalf to create the string. The malloc() call gets diverted into my function in cmemory.c, which calls instrumentMalloc(). As that's Go code, control flow goes back into the runtime. Something in there breaks, causing the runtime to think the malloc() failed and kill the program. I don't know _what_ that is except it happened sometime after Go 1.3.

The upside is that shouldn't affect memory allocations that are actually done from within C. Allocation on the C stack from within Go, like what you did in that code snippet, could be done with my Memory struct if they were altered to use libc's malloc() and bypass the instrumentation (leak checks are unnecessary there since they call free() on the C block when GC'ed). I could also change the instrumentation so that it's done entirely in C and just stores data that's read by Go separately later, but I don't have the time anymore to do that sort of rearchitecting :'(
